const reflectionPrompts = [
    "What progress did you make in your practice today?",
    "What is one thing you learned that made you better?",
    "How did you challenge yourself during practice today?",
    "What goal did you work on today, and how close are you to achieving it?",
    "What can you do tomorrow to build on today’s progress?",
    "What mistakes did you make, and what did you learn from them?",
    "What did you do today that you couldn’t do a week ago?",
    "What is one skill you want to improve, and how will you work on it?",
    "What helped you stay motivated during practice?",
    "How did you stay positive when things got hard today?",
    "What part of your practice helped you feel successful?",
    "What is one step you can take to improve a tricky section tomorrow?",
    "How did you use feedback from your last lesson to grow today?",
    "What strategy worked best for you today?",
    "What small victory did you achieve during practice?",
    "What goal are you most excited to work on next time?",
    "What did you practice slowly today to get it right?",
    "How did you track your progress during practice?",
    "What is one thing you pushed yourself to do better today?",
    "How did you make sure to stay focused on your goals?",
    "What did you notice about your playing that you want to improve?",
    "What part of today’s practice made you feel proud of your effort?",
    "What did you learn about yourself as a musician today?",
    "What new habit are you building with your practice?",
    "How did you try to make the hard parts easier today?",
    "What is one long-term goal you worked toward today?",
    "What will you do differently tomorrow to improve even more?",
    "How did you stay calm and focused when something was difficult?",
    "What is one thing you practiced today that felt like real progress?",
    "How did you stay curious about what you were practicing?",
    "What did you do today to prepare for your next lesson?",
    "How did you connect today’s practice to your bigger goals?",
    "What is one thing you can do to practice more effectively tomorrow?",
    "What inspired you to keep going when it got challenging?",
    "What is one thing you’re closer to mastering after today?",
    "How did you celebrate small wins during your practice?",
    "What are you most proud of accomplishing today?",
    "How did you make today’s practice a step toward your goals?",
    "What adjustment did you make to improve your playing?",
    "How did you try to make your playing more expressive today?",
    "What is one thing you tried today that worked well?",
    "How did you plan your practice time to reach your goals?",
    "What mistake helped you learn something new today?",
    "How did you make sure to keep improving during practice?",
    "What is one thing you thought you couldn’t do but did anyway?",
    "What did you discover about your music today?",
    "How did you make the most of your time while practicing?",
    "What is one area where you grew stronger today?",
    "How will today’s practice help you reach your goals?",
    "What did you do today that showed a growth mindset?",
    "What did you enjoy most about your practice today?",
    "How did you challenge yourself to play with more feeling today?",
    "What is one thing that felt hard at first but got easier as you practiced?",
    "How did you stay patient with yourself while practicing today?",
    "What did you do to make practice more fun or creative today?",
    "What part of your practice showed how much you’ve improved?",
    "What advice would you give yourself about today’s practice?",
    "What is something new you tried today, and how did it help?",
    "How did you turn a challenge into an opportunity to grow?",
    "What is one thing you’re excited to keep working on tomorrow?",
    "How did you use your strengths to make practice successful today?",
    "What did you notice about your technique that helped you play better?",
    "How did you set yourself up for success before you started practicing?",
    "What was the most surprising thing you learned during practice?",
    "How did breaking a big goal into smaller steps help you today?",
    "What helped you stay focused and avoid distractions during practice?",
    "What positive thoughts kept you going when practice was tough?",
    "How did you balance working on new skills and reviewing old ones?",
    "What is one thing you want to explore more in your music?",
    "How did you show persistence during a difficult section today?",
    "What is one small change you made that had a big impact?",
    "How did you make sure to listen carefully to your playing today?",
    "What is one thing you can practice differently to improve faster?",
    "What did you do today that showed you’re becoming a better musician?",
    "How did you use your imagination to connect with the music today?",
    "What is one goal you can set for your practice tomorrow?",
    "How did you feel after finishing your practice today?",
    "What advice would you give to someone just starting their practice?",
    "How did you use a past mistake to make progress today?",
    "What is one thing you can do to make practice more enjoyable tomorrow?",
    "How did you show bravery by trying something new today?",
    "What part of today’s practice gave you the most confidence?",
    "What is one thing you wish you’d done differently in practice today?",
    "How did you take time to appreciate your hard work today?",
    "What is one thing you learned about music from today’s practice?",
    "How did you experiment with a new way of practicing today?",
    "What is something that went well because of your preparation?",
    "What helped you remember to focus on the details today?",
    "How did you stay patient when a section didn’t go as planned?",
    "What is one thing you practiced today that will help you long-term?",
    "How did you celebrate the progress you’ve made so far?",
    "What did you do today that made you feel more confident as a musician?",
    "How did practicing help you enjoy your music more today?",
    "What did you do today that showed you were pushing yourself to grow?",
    "What is one thing you discovered about the music you’re learning?",
    "How did you find a way to enjoy even the hardest parts of practice?",
    "What is one thing you would teach someone else about your practice today?",
    "How did you take time to reflect on your progress during practice?"
  ];

  function randomPrompt(): string {
    const n = reflectionPrompts.length - 1;
    const i = Math.floor(Math.random() * n);
    return reflectionPrompts[i];
  }
  export default randomPrompt;